# Generated by Django 3.0 on 2020-06-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('products', '0002_product_description'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='production_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='areas.ProductionLine'),
            preserve_default=False,
        ),
    ]
