# Generated by Django 3.0 on 2020-06-18 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20200618_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('boolean', models.BooleanField(default=True, verbose_name='This is a boolean Field')),
                ('char', models.CharField(help_text='This is the help text', max_length=220, unique=True, verbose_name='New Name')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('decimal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('email', models.EmailField(max_length=200)),
                ('file', models.FileField(blank=True, upload_to='uploads')),
                ('image', models.ImageField(blank=True, upload_to='uploads')),
                ('integer', models.IntegerField()),
                ('pos_sm_int', models.PositiveIntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('text', models.TextField()),
                ('url', models.URLField()),
                ('uuid1', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_time', models.DateTimeField()),
                ('choice', models.CharField(choices=[('one', 'number one'), ('two', 'number two')], max_length=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('new_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
